// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConversationController from "./conversation_controller"
application.register("conversation", ConversationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CharacterFormController from "./character_form_controller"
Stimulus.register("character-form", CharacterFormController)

import CharacterSelectionController from "./character_selection_controller"
Stimulus.register("character-selection", CharacterSelectionController)

import ClosableController from "./closable_controllerr"
Stimulus.register("closable", ClosableController)